Stratum v1
Foundation-Devices/foundation-rs pull request #42
Opened 2024-08-28 13:06 UTC by georgesFoundation

Add a no_std no_alloc Stratum v1 client crate

2024-08-28 13:40 UTC, georgesFoundation commented
Note, I still can't `cargo package` it until faster-hex merge and publish nervosnetwork/faster-hex/pull/48 and nervosnetwork/faster-hex/pull/49

2024-08-29 11:29 UTC, jeandudey requested changes
Nice! LGTM, just some nit picks

2024-08-29 11:29 UTC, jeandudey commented on Cargo.toml
> +derive_more = { version = "1.0.0-beta", default-features = false }
I think the `1.0.0` version is out of beta now: https://crates.io/crates/derive_more/1.0.0

2024-08-29 11:29 UTC, jeandudey commented on stratum-v1/src/client/request.rs
> +    pub method: String<23>,
I think this is a typo? e.g. 23 -> 32?

2024-08-29 12:09 UTC, georgesFoundation commented on Cargo.toml
> +derive_more = { version = "1.0.0-beta", default-features = false }
great !

2024-08-29 12:11 UTC, georgesFoundation commented on stratum-v1/src/client/request.rs
> +    pub method: String<23>,
good catch !

2024-08-30 10:07 UTC, jeandudey approved these changes
LGTM!

2024-09-16 14:25 UTC, merged